require 'spec_helper'
require 'amazon_sp_clients/v2'
require_relative '../../lib/generator'

# The V2 template set, rendered from a small fixture spec and loaded
# for real, so the generated calling convention is pinned here and the
# committed output only has to match `rake generate:verify`.
RSpec.describe 'V2 code generation' do
  v2 = AmazonSpClients::V2
  fixtures = File.expand_path('../fixtures/generator', __dir__)

  let(:api_module) do
    Generator::ApiModule.new(name: 'things_v1', spec_path: 'things.json',
                             templates: %w[v2], models_dir: fixtures)
  end
  let(:source) { api_module.render_v2 }

  # Loads the generated class once for the whole group.
  def things_class
    namespace = AmazonSpClients::V2
    return namespace::ThingsV1 if namespace.const_defined?(:ThingsV1)

    Object.class_eval(source)
    namespace::ThingsV1
  end

  describe 'module config' do
    it 'requires a template list with known names' do
      expect { Generator::ApiModule.new(name: 'x', spec_path: 'x.json', templates: %w[v3]) }
        .to raise_error(ArgumentError, /v3/)
      expect { Generator::ApiModule.new(name: 'x', spec_path: 'x.json', templates: []) }
        .to raise_error(ArgumentError)
    end

    it 'names the V2 class and file after the module' do
      expect(api_module.v2_class_name).to eq('ThingsV1')
      expect(api_module.owned_paths).to eq(['lib/amazon_sp_clients/v2/apis/things_v1.rb'])
    end

    it 'owns the v1 paths too when v1 is listed' do
      both = Generator::ApiModule.new(name: 'things_v1', spec_path: 'things.json',
                                      templates: %w[v1 v2], models_dir: fixtures)

      expect(both.owned_paths).to eq(
        %w[
          vendor/things_v1/lib/sp_things_v1.rb
          vendor/things_v1/lib/sp_things_v1/api
          lib/amazon_sp_clients/sp_things_v1.rb
          lib/amazon_sp_clients/v2/apis/things_v1.rb
        ]
      )
    end
  end

  describe 'rendered class' do
    it 'is one Api subclass per module, with every tag merged and sorted' do
      klass = things_class

      expect(klass.superclass).to be(v2::Api)
      expect(klass.public_instance_methods(false).sort)
        .to eq(%i[cancel_thing create_thing list_things])
      expect(source.index('def cancel_thing')).to be < source.index('def create_thing')
      expect(source.index('def create_thing')).to be < source.index('def list_things')
    end

    it 'keeps required params positional in v1 order and makes the rest keywords' do
      expect(things_class.instance_method(:list_things).parameters).to eq(
        [%i[req ids], %i[key next_token], %i[key details], %i[key max_results], %i[key rdt]]
      )
      expect(things_class.instance_method(:create_thing).parameters).to eq(
        [%i[req body], %i[req thing_id], %i[req x_amzn_idempotency_token], %i[key rdt]]
      )
    end

    it 'documents every method for YARD, once and unescaped' do
      expect(source).to include('# @param ids [Array<String>] Thing ids.')
      expect(source).to include('# @param details [Boolean, nil] Include details.')
      expect(source).to include('# @param max_results [Integer, nil] Page size.')
      expect(source).to include('# @param body [Hash] The request. (CreateThingRequest)')
      expect(source).to include('# @param rdt [Array<RDT::Resource>, nil]')
      expect(source).to include('# @return [AmazonSpClients::ApiResponse]')
      expect(source).to include('see the `x-amzn-RateLimit-Limit` header')
      expect(source).not_to include('=begin')
      expect(source).not_to include('&#x60;')
      expect(source).to include("# Manage things. Second line.\n")
    end

    it 'starts with the generated-file notice and no v1 references' do
      expect(source).to start_with("# frozen_string_literal: true\n\n# Generated by lib/generator")
      expect(source).not_to include('ApiClient')
      expect(source).not_to include('auth_names')
    end
  end

  describe 'generated methods on the wire' do
    let(:base_url) { 'https://sellingpartnerapi-na.amazon.com' }
    let(:client) { v2::Client.new(v2::Config.new) { 'ACCESS' } }
    let(:api) { things_class.new(client) }

    it 'sends required and given optional params, joining arrays and dropping nils' do
      stub = stub_request(:get, "#{base_url}/things/v1/things")
             .with(query: { 'Ids' => 'A,B', 'details' => 'false' })
             .to_return(status: 200, body: '{"payload":{"things":[]}}')

      response = api.list_things(%w[A B], details: false)

      expect(stub).to have_been_requested
      expect(response.payload).to eq(things: [])
    end

    it 'sends no optional params when none are given' do
      stub = stub_request(:get, "#{base_url}/things/v1/things")
             .with(query: { 'Ids' => 'A' })
             .to_return(status: 200, body: '{}')

      api.list_things(['A'])

      expect(stub).to have_been_requested
    end

    it 'encodes path params and sends header params and the JSON body' do
      stub = stub_request(:post, "#{base_url}/things/v1/things/x%20y")
             .with(body: '{"name":"n"}', headers: { 'x-amzn-idempotency-token' => 'TOKEN' })
             .to_return(status: 200, body: '{}')

      api.create_thing({ name: 'n' }, 'x y', 'TOKEN')

      expect(stub).to have_been_requested
    end

    it 'returns an ApiResponse for an operation without a response schema' do
      stub_request(:delete, "#{base_url}/things/v1/things/T1/cancel")
        .to_return(status: 204, body: '', headers: { 'x-amzn-RateLimit-Limit' => '1' })

      response = api.cancel_thing('T1')

      expect(response).to be_a(AmazonSpClients::ApiResponse)
      expect(response.reported_rate_limit).to eq(1.0)
    end

    it 'passes rdt through' do
      tokens = stub_request(:post, "#{base_url}/tokens/2021-03-01/restrictedDataToken")
               .to_return(status: 200, body: '{"restrictedDataToken":"RDT","expiresIn":3600}')
      stub_request(:get, "#{base_url}/things/v1/things")
        .with(query: { 'Ids' => 'A' }, headers: { 'x-amz-access-token' => 'RDT' })
        .to_return(status: 200, body: '{}')

      api.list_things(['A'], rdt: [v2::RDT.resource('GET', '/things/v1/things')])

      expect(tokens).to have_been_requested
    end

    it 'rejects option keys that are not parameters' do
      expect { api.list_things(['A'], order_status: 'Shipped') }
        .to raise_error(ArgumentError, /order_status/)
    end
  end

  describe 'name guard' do
    names = Generator::Names

    it 'rejects parameter names Ruby or the V2 signature already use' do
      expect { names.check_param!('end', operation: 'op') }.to raise_error(/end/)
      expect { names.check_param!('rdt', operation: 'op') }.to raise_error(/rdt/)
      expect { names.check_param!('body', operation: 'op') }.to raise_error(/body/)
      expect { names.check_param!('next_token', operation: 'op') }.not_to raise_error
    end

    it 'rejects method names that collide with Ruby, Object or the Api base' do
      expect { names.check_method!('class') }.to raise_error(/class/)
      expect { names.check_method!('freeze') }.to raise_error(/freeze/)
      expect { names.check_method!('request') }.to raise_error(/request/)
      expect { names.check_method!('csv') }.to raise_error(/csv/)
      expect { names.check_method!('get_orders') }.not_to raise_error
    end

    it 'rejects module names that collide with Client methods' do
      expect { names.check_module!('request') }.to raise_error(/request/)
      expect { names.check_module!('api') }.to raise_error(/api/)
      expect { names.check_module!('orders_v0') }.not_to raise_error
    end

    it 'rejects duplicates after snake_casing' do
      expect { names.check_unique!(%w[getThing GetThing], what: 'operationId') }
        .to raise_error(/get_thing/)
      expect { names.check_unique!(%w[NextToken nextToken], what: 'parameter') }
        .to raise_error(/next_token/)
      expect { names.check_unique!(%w[a b], what: 'parameter') }.not_to raise_error
    end
  end

  describe 'apis entry file' do
    let(:entry) { Generator.render_v2_apis([api_module]) }

    it 'autoloads each class and gives Client an accessor per module' do
      expect(entry).to include("autoload :ThingsV1, 'amazon_sp_clients/v2/apis/things_v1'")
      expect(entry).to include('def things_v1 = api(ThingsV1)')
      expect(entry).to include("# Selling Partner API for Things\n")
    end

    it 'loads and hands out the memoized API instance' do
      things_class
      Object.class_eval(entry)
      client = v2::Client.new(v2::Config.new) { 'ACCESS' }

      expect(client.things_v1).to be_a(v2::ThingsV1)
      expect(client.things_v1).to be(client.things_v1)
    end
  end
end
