# frozen_string_literal: true

# Generated by lib/generator (bundle exec rake generate). Do not edit.

require 'amazon_sp_clients/v2/api'

module AmazonSpClients
  module V2
    # Selling Partner API for FBA Inventory
    #
    # The Selling Partner API for FBA Inventory lets you programmatically retrieve information about inventory in Amazon's fulfillment network.
    #
    # OpenAPI spec version: v1
    class FbaInventory < Api
      # Requests that Amazon add items to the Sandbox Inventory with desired amount of quantity in the sandbox environment. This is a sandbox-only operation and must be directed to a sandbox endpoint. Refer to [Selling Partner API sandbox](https://developer-docs.amazon.com/sp-api/docs/the-selling-partner-api-sandbox) for more information.
      #
      # @param body [Hash] List of items to add to Sandbox inventory. (AddInventoryRequest)
      # @param x_amzn_idempotency_token [String] A unique token/requestId provided with each call to ensure idempotency.
      # @param rdt [Array<RDT::Resource>, nil] send a restricted data token for these resources
      # @return [AmazonSpClients::ApiResponse]
      def add_inventory(body, x_amzn_idempotency_token, rdt: nil)
        headers = {
          'x-amzn-idempotency-token' => x_amzn_idempotency_token
        }

        request(:post, '/fba/inventory/v1/items/inventory', headers: headers, body: body, rdt: rdt)
      end

      # Requests that Amazon create product-details in the Sandbox Inventory in the sandbox environment. This is a sandbox-only operation and must be directed to a sandbox endpoint. Refer to [Selling Partner API sandbox](https://developer-docs.amazon.com/sp-api/docs/the-selling-partner-api-sandbox) for more information.
      #
      # @param body [Hash] CreateInventoryItem Request Body Parameter. (CreateInventoryItemRequest)
      # @param rdt [Array<RDT::Resource>, nil] send a restricted data token for these resources
      # @return [AmazonSpClients::ApiResponse]
      def create_inventory_item(body, rdt: nil)
        request(:post, '/fba/inventory/v1/items', body: body, rdt: rdt)
      end

      # Requests that Amazon Deletes an item from the Sandbox Inventory in the sandbox environment. This is a sandbox-only operation and must be directed to a sandbox endpoint. Refer to [Selling Partner API sandbox](https://developer-docs.amazon.com/sp-api/docs/the-selling-partner-api-sandbox) for more information.
      #
      # @param seller_sku [String] A single seller SKU used for querying the specified seller SKU inventory summaries.
      # @param marketplace_id [String] The marketplace ID for the marketplace for which the sellerSku is to be deleted.
      # @param rdt [Array<RDT::Resource>, nil] send a restricted data token for these resources
      # @return [AmazonSpClients::ApiResponse]
      def delete_inventory_item(seller_sku, marketplace_id, rdt: nil)
        query = {
          'marketplaceId' => marketplace_id
        }

        request(:delete, "/fba/inventory/v1/items/#{encode(seller_sku)}", query: query, rdt: rdt)
      end

      # Returns a list of inventory summaries. The summaries returned depend on the presence or absence of the startDateTime, sellerSkus and sellerSku parameters: - All inventory summaries with available details are returned when the startDateTime, sellerSkus and sellerSku parameters are omitted. - When startDateTime is provided, the operation returns inventory summaries that have had changes after the date and time specified. The sellerSkus and sellerSku parameters are ignored. Important: To avoid errors, use both startDateTime and nextToken to get the next page of inventory summaries that have changed after the date and time specified. - When the sellerSkus parameter is provided, the operation returns inventory summaries for only the specified sellerSkus. The sellerSku parameter is ignored. - When the sellerSku parameter is provided, the operation returns inventory summaries for only the specified sellerSku. Note: The parameters associated with this operation may contain special characters that must be encoded to successfully call the API. To avoid errors with SKUs when encoding URLs, refer to [URL Encoding](https://developer-docs.amazon.com/sp-api/docs/url-encoding). Usage Plan: | Rate (requests per second) | Burst | | ---- | ---- | | 2 | 2 | The x-amzn-RateLimit-Limit response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits).
      #
      # @param granularity_type [String] The granularity type for the inventory aggregation level.
      # @param granularity_id [String] The granularity ID for the inventory aggregation level.
      # @param marketplace_ids [Array<String>] The marketplace ID for the marketplace for which to return inventory summaries.
      # @param details [Boolean, nil] true to return inventory summaries with additional summarized inventory details and quantities. Otherwise, returns inventory summaries only (default value).
      # @param start_date_time [String, nil] A start date and time in ISO8601 format. If specified, all inventory summaries that have changed since then are returned. You must specify a date and time that is no earlier than 18 months prior to the date and time when you call the API. Note: Changes in inboundWorkingQuantity, inboundShippedQuantity and inboundReceivingQuantity are not detected.
      # @param seller_skus [Array<String>, nil] A list of seller SKUs for which to return inventory summaries. You may specify up to 50 SKUs.
      # @param seller_sku [String, nil] A single seller SKU used for querying the specified seller SKU inventory summaries.
      # @param next_token [String, nil] String token returned in the response of your previous request. The string token will expire 30 seconds after being created.
      # @param rdt [Array<RDT::Resource>, nil] send a restricted data token for these resources
      # @return [AmazonSpClients::ApiResponse]
      def get_inventory_summaries(granularity_type, granularity_id, marketplace_ids, details: nil, start_date_time: nil, seller_skus: nil, seller_sku: nil, next_token: nil, rdt: nil)
        query = {
          'details' => details,
          'granularityType' => granularity_type,
          'granularityId' => granularity_id,
          'startDateTime' => start_date_time,
          'sellerSkus' => csv(seller_skus),
          'sellerSku' => seller_sku,
          'nextToken' => next_token,
          'marketplaceIds' => csv(marketplace_ids)
        }

        request(:get, '/fba/inventory/v1/summaries', query: query, rdt: rdt)
      end
    end
  end
end
