# frozen_string_literal: true

# Generated by lib/generator (bundle exec rake generate). Do not edit.

require 'amazon_sp_clients/v2/api'

module AmazonSpClients
  module V2
    # Selling Partner API for Feeds
    #
    # The Selling Partner API for Feeds lets you upload data to Amazon on behalf of a selling partner.
    #
    # OpenAPI spec version: 2021-06-30
    class Feeds2021 < Api
      # Cancels the feed that you specify. Only feeds with `processingStatus=IN_QUEUE` can be cancelled. Cancelled feeds are returned in subsequent calls to the [`getFeed`](https://developer-docs.amazon.com/sp-api/docs/feeds-api-v2021-06-30-reference#getfeed) and [`getFeeds`](https://developer-docs.amazon.com/sp-api/docs/feeds-api-v2021-06-30-reference#getfeeds) operations. **Usage Plan:** | Rate (requests per second) | Burst | | ---- | ---- | | 2 | 15 | The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
      #
      # @param feed_id [String] The identifier for the feed. This identifier is unique only in combination with a seller ID.
      # @param rdt [Array<RDT::Resource>, nil] send a restricted data token for these resources
      # @return [AmazonSpClients::ApiResponse]
      def cancel_feed(feed_id, rdt: nil)
        request(:delete, "/feeds/2021-06-30/feeds/#{encode(feed_id)}", rdt: rdt)
      end

      # Creates a feed. Upload the contents of the feed document before calling this operation. **Usage Plan:** | Rate (requests per second) | Burst | | ---- | ---- | | 0.0083 | 15 | The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api). The rate limit for the [`JSON_LISTINGS_FEED`](https://developer-docs.amazon.com/sp-api/docs/listings-feed-type-values#listings-feed) feed type differs from the rate limit for the [`createFeed`](https://developer-docs.amazon.com/sp-api/docs/feeds-api-v2021-06-30-reference#post-feeds2021-06-30feeds) operation. For more information, refer to the [Building Listings Management Workflows Guide](https://developer-docs.amazon.com/sp-api/docs/building-listings-management-workflows-guide#should-i-submit-in-bulk-using-the-json_listings_feed-or-individually-with-the-listings-items-api).
      #
      # @param body [Hash] Information required to create the feed. (CreateFeedSpecification)
      # @param rdt [Array<RDT::Resource>, nil] send a restricted data token for these resources
      # @return [AmazonSpClients::ApiResponse]
      def create_feed(body, rdt: nil)
        request(:post, '/feeds/2021-06-30/feeds', body: body, rdt: rdt)
      end

      # Creates a feed document for the feed type that you specify. This operation returns a presigned URL for uploading the feed document contents. It also returns a `feedDocumentId` value that you can pass in with a subsequent call to the [`createFeed`](https://developer-docs.amazon.com/sp-api/docs/feeds-api-v2021-06-30-reference#createfeed) operation. **Usage Plan:** | Rate (requests per second) | Burst | | ---- | ---- | | 0.5 | 15 | The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
      #
      # @param body [Hash] Specifies the content type for the createFeedDocument operation. (CreateFeedDocumentSpecification)
      # @param rdt [Array<RDT::Resource>, nil] send a restricted data token for these resources
      # @return [AmazonSpClients::ApiResponse]
      def create_feed_document(body, rdt: nil)
        request(:post, '/feeds/2021-06-30/documents', body: body, rdt: rdt)
      end

      # Returns feed details (including the `resultDocumentId`, if available) for the feed that you specify. **Usage Plan:** | Rate (requests per second) | Burst | | ---- | ---- | | 2 | 15 | The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
      #
      # @param feed_id [String] The identifier for the feed. This identifier is unique only in combination with a seller ID.
      # @param rdt [Array<RDT::Resource>, nil] send a restricted data token for these resources
      # @return [AmazonSpClients::ApiResponse]
      def get_feed(feed_id, rdt: nil)
        request(:get, "/feeds/2021-06-30/feeds/#{encode(feed_id)}", rdt: rdt)
      end

      # Returns the information required for retrieving a feed document's contents. **Usage Plan:** | Rate (requests per second) | Burst | | ---- | ---- | | 0.0222 | 10 | The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
      #
      # @param feed_document_id [String] The identifier of the feed document.
      # @param rdt [Array<RDT::Resource>, nil] send a restricted data token for these resources
      # @return [AmazonSpClients::ApiResponse]
      def get_feed_document(feed_document_id, rdt: nil)
        request(:get, "/feeds/2021-06-30/documents/#{encode(feed_document_id)}", rdt: rdt)
      end

      # Returns feed details for the feeds that match the filters that you specify. **Usage Plan:** | Rate (requests per second) | Burst | | ---- | ---- | | 0.0222 | 10 | The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
      #
      # @param feed_types [Array<String>, nil] A list of feed types used to filter feeds. When feedTypes is provided, the other filter parameters (processingStatuses, marketplaceIds, createdSince, createdUntil) and pageSize may also be provided. Either feedTypes or nextToken is required.
      # @param marketplace_ids [Array<String>, nil] A list of marketplace identifiers used to filter feeds. The feeds returned will match at least one of the marketplaces that you specify.
      # @param page_size [Integer, nil] The maximum number of feeds to return in a single call.
      # @param processing_statuses [Array<String>, nil] A list of processing statuses used to filter feeds.
      # @param created_since [String, nil] The earliest feed creation date and time for feeds included in the response, in ISO 8601 format. The default is 90 days ago. Feeds are retained for a maximum of 90 days.
      # @param created_until [String, nil] The latest feed creation date and time for feeds included in the response, in ISO 8601 format. The default is now.
      # @param next_token [String, nil] A string token returned in the response to your previous request. nextToken is returned when the number of results exceeds the specified pageSize value. To get the next page of results, call the getFeeds operation and include this token as the only parameter. Specifying nextToken with any other parameters will cause the request to fail.
      # @param rdt [Array<RDT::Resource>, nil] send a restricted data token for these resources
      # @return [AmazonSpClients::ApiResponse]
      def get_feeds(feed_types: nil, marketplace_ids: nil, page_size: nil, processing_statuses: nil, created_since: nil, created_until: nil, next_token: nil, rdt: nil)
        query = {
          'feedTypes' => csv(feed_types),
          'marketplaceIds' => csv(marketplace_ids),
          'pageSize' => page_size,
          'processingStatuses' => csv(processing_statuses),
          'createdSince' => created_since,
          'createdUntil' => created_until,
          'nextToken' => next_token
        }

        request(:get, '/feeds/2021-06-30/feeds', query: query, rdt: rdt)
      end
    end
  end
end
