# frozen_string_literal: true

# Generated by lib/generator (bundle exec rake generate). Do not edit.

require 'amazon_sp_clients/v2/api'

module AmazonSpClients
  module V2
    # Selling Partner APIs for Fulfillment Outbound
    #
    # The Selling Partner API for Fulfillment Outbound lets you create applications that help a seller fulfill Multi-Channel Fulfillment orders using their inventory in Amazon's fulfillment network. You can get information on both potential and existing fulfillment orders.
    #
    # OpenAPI spec version: 2020-07-01
    class FulfillmentOutbound2020 < Api
      # Requests that Amazon stop attempting to fulfill the fulfillment order indicated by the specified order identifier. **Usage Plan:** | Rate (requests per second) | Burst | | ---- | ---- | | 2 | 30 | The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
      #
      # @param seller_fulfillment_order_id [String] The identifier assigned to the item by the seller when the fulfillment order was created.
      # @param rdt [Array<RDT::Resource>, nil] send a restricted data token for these resources
      # @return [AmazonSpClients::ApiResponse]
      def cancel_fulfillment_order(seller_fulfillment_order_id, rdt: nil)
        request(:put, "/fba/outbound/2020-07-01/fulfillmentOrders/#{encode(seller_fulfillment_order_id)}/cancel", rdt: rdt)
      end

      # Requests that Amazon ship items from the seller's inventory in Amazon's fulfillment network to a destination address. **Usage Plan:** | Rate (requests per second) | Burst | | ---- | ---- | | 2 | 30 | The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api)
      #
      # @param body [Hash] CreateFulfillmentOrderRequest parameter (CreateFulfillmentOrderRequest)
      # @param rdt [Array<RDT::Resource>, nil] send a restricted data token for these resources
      # @return [AmazonSpClients::ApiResponse]
      def create_fulfillment_order(body, rdt: nil)
        request(:post, '/fba/outbound/2020-07-01/fulfillmentOrders', body: body, rdt: rdt)
      end

      # Creates a fulfillment return. **Usage Plan:** | Rate (requests per second) | Burst | | ---- | ---- | | 2 | 30 | The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
      #
      # @param body [Hash] CreateFulfillmentReturnRequest parameter (CreateFulfillmentReturnRequest)
      # @param seller_fulfillment_order_id [String] An identifier assigned by the seller to the fulfillment order at the time it was created. The seller uses their own records to find the correct `SellerFulfillmentOrderId` value based on the buyer's request to return items.
      # @param rdt [Array<RDT::Resource>, nil] send a restricted data token for these resources
      # @return [AmazonSpClients::ApiResponse]
      def create_fulfillment_return(body, seller_fulfillment_order_id, rdt: nil)
        request(:put, "/fba/outbound/2020-07-01/fulfillmentOrders/#{encode(seller_fulfillment_order_id)}/return", body: body, rdt: rdt)
      end

      # Returns delivery options that include an estimated delivery date and offer expiration, based on criteria that you specify. **Usage Plan:** | Rate (requests per second) | Burst | | ---- | ---- | | 5 | 30 | The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
      #
      # @param body [Hash] GetDeliveryOffersRequest parameter (GetDeliveryOffersRequest)
      # @param rdt [Array<RDT::Resource>, nil] send a restricted data token for these resources
      # @return [AmazonSpClients::ApiResponse]
      def delivery_offers(body, rdt: nil)
        request(:post, '/fba/outbound/2020-07-01/deliveryOffers', body: body, rdt: rdt)
      end

      # Returns a list of inventory items that are eligible for the fulfillment feature you specify. **Usage Plan:** | Rate (requests per second) | Burst | | ---- | ---- | | 2 | 30 | The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api)..
      #
      # @param marketplace_id [String] The marketplace for which to return a list of the inventory that is eligible for the specified feature.
      # @param feature_name [String] The name of the feature for which to return a list of eligible inventory.
      # @param next_token [String, nil] A string token returned in the response to your previous request that is used to return the next response page. A value of null will return the first page.
      # @param query_start_date [String, nil] A date that you can use to select inventory that has been updated since a specified date. An update is defined as any change in feature-enabled inventory availability. The date must be in the format yyyy-MM-ddTHH:mm:ss.sssZ
      # @param rdt [Array<RDT::Resource>, nil] send a restricted data token for these resources
      # @return [AmazonSpClients::ApiResponse]
      def get_feature_inventory(marketplace_id, feature_name, next_token: nil, query_start_date: nil, rdt: nil)
        query = {
          'marketplaceId' => marketplace_id,
          'nextToken' => next_token,
          'queryStartDate' => query_start_date
        }

        request(:get, "/fba/outbound/2020-07-01/features/inventory/#{encode(feature_name)}", query: query, rdt: rdt)
      end

      # Returns the number of items with the sellerSKU you specify that can have orders fulfilled using the specified feature. Note that if the sellerSKU isn't eligible, the response will contain an empty skuInfo object. The parameters for this operation may contain special characters that require URL encoding. To avoid errors with SKUs when encoding URLs, refer to [URL Encoding](https://developer-docs.amazon.com/sp-api/docs/url-encoding). **Usage Plan:** | Rate (requests per second) | Burst | | ---- | ---- | | 2 | 30 | The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
      #
      # @param marketplace_id [String] The marketplace for which to return the count.
      # @param feature_name [String] The name of the feature.
      # @param seller_sku [String] Used to identify an item in the given marketplace. `SellerSKU` is qualified by the seller's `SellerId`, which is included with every operation that you submit.
      # @param rdt [Array<RDT::Resource>, nil] send a restricted data token for these resources
      # @return [AmazonSpClients::ApiResponse]
      def get_feature_sku(marketplace_id, feature_name, seller_sku, rdt: nil)
        query = {
          'marketplaceId' => marketplace_id
        }

        request(:get, "/fba/outbound/2020-07-01/features/inventory/#{encode(feature_name)}/#{encode(seller_sku)}", query: query, rdt: rdt)
      end

      # Returns a list of features available for Multi-Channel Fulfillment orders in the marketplace you specify, and whether the seller for which you made the call is enrolled for each feature. **Usage Plan:** | Rate (requests per second) | Burst | | ---- | ---- | | 2 | 30 | The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
      #
      # @param marketplace_id [String] The marketplace for which to return the list of features.
      # @param rdt [Array<RDT::Resource>, nil] send a restricted data token for these resources
      # @return [AmazonSpClients::ApiResponse]
      def get_features(marketplace_id, rdt: nil)
        query = {
          'marketplaceId' => marketplace_id
        }

        request(:get, '/fba/outbound/2020-07-01/features', query: query, rdt: rdt)
      end

      # Returns the fulfillment order indicated by the specified order identifier. **Usage Plan:** | Rate (requests per second) | Burst | | ---- | ---- | | 2 | 30 | The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
      #
      # @param seller_fulfillment_order_id [String] The identifier assigned to the item by the seller when the fulfillment order was created.
      # @param rdt [Array<RDT::Resource>, nil] send a restricted data token for these resources
      # @return [AmazonSpClients::ApiResponse]
      def get_fulfillment_order(seller_fulfillment_order_id, rdt: nil)
        request(:get, "/fba/outbound/2020-07-01/fulfillmentOrders/#{encode(seller_fulfillment_order_id)}", rdt: rdt)
      end

      # Returns a list of fulfillment order previews based on shipping criteria that you specify. **Usage Plan:** | Rate (requests per second) | Burst | | ---- | ---- | | 2 | 30 | The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
      #
      # @param body [Hash] GetFulfillmentPreviewRequest parameter (GetFulfillmentPreviewRequest)
      # @param rdt [Array<RDT::Resource>, nil] send a restricted data token for these resources
      # @return [AmazonSpClients::ApiResponse]
      def get_fulfillment_preview(body, rdt: nil)
        request(:post, '/fba/outbound/2020-07-01/fulfillmentOrders/preview', body: body, rdt: rdt)
      end

      # Returns delivery tracking information for a package in an outbound shipment for a Multi-Channel Fulfillment order. **Usage Plan:** | Rate (requests per second) | Burst | | ---- | ---- | | 2 | 30 | The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
      #
      # @param package_number [Integer] The unencrypted package identifier returned by the `getFulfillmentOrder` operation.
      # @param rdt [Array<RDT::Resource>, nil] send a restricted data token for these resources
      # @return [AmazonSpClients::ApiResponse]
      def get_package_tracking_details(package_number, rdt: nil)
        query = {
          'packageNumber' => package_number
        }

        request(:get, '/fba/outbound/2020-07-01/tracking', query: query, rdt: rdt)
      end

      # Returns a list of fulfillment orders fulfilled after (or at) a specified date-time, or indicated by the next token parameter. **Usage Plan:** | Rate (requests per second) | Burst | | ---- | ---- | | 2 | 30 | The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api)
      #
      # @param query_start_date [String, nil] A date used to select fulfillment orders that were last updated after (or at) a specified time. An update is defined as any change in fulfillment order status, including the creation of a new fulfillment order.
      # @param next_token [String, nil] A string token returned in the response to your previous request.
      # @param rdt [Array<RDT::Resource>, nil] send a restricted data token for these resources
      # @return [AmazonSpClients::ApiResponse]
      def list_all_fulfillment_orders(query_start_date: nil, next_token: nil, rdt: nil)
        query = {
          'queryStartDate' => query_start_date,
          'nextToken' => next_token
        }

        request(:get, '/fba/outbound/2020-07-01/fulfillmentOrders', query: query, rdt: rdt)
      end

      # Returns a list of return reason codes for a seller SKU in a given marketplace. The parameters for this operation may contain special characters that require URL encoding. To avoid errors with SKUs when encoding URLs, refer to [URL Encoding](https://developer-docs.amazon.com/sp-api/docs/url-encoding). **Usage Plan:** | Rate (requests per second) | Burst | | ---- | ---- | | 2 | 30 | The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
      #
      # @param seller_sku [String] The seller SKU for which return reason codes are required.
      # @param marketplace_id [String, nil] The marketplace for which the seller wants return reason codes.
      # @param seller_fulfillment_order_id [String, nil] The identifier assigned to the item by the seller when the fulfillment order was created. The service uses this value to determine the marketplace for which the seller wants return reason codes.
      # @param language [String, nil] The language that the `TranslatedDescription` property of the `ReasonCodeDetails` response object should be translated into.
      # @param rdt [Array<RDT::Resource>, nil] send a restricted data token for these resources
      # @return [AmazonSpClients::ApiResponse]
      def list_return_reason_codes(seller_sku, marketplace_id: nil, seller_fulfillment_order_id: nil, language: nil, rdt: nil)
        query = {
          'sellerSku' => seller_sku,
          'marketplaceId' => marketplace_id,
          'sellerFulfillmentOrderId' => seller_fulfillment_order_id,
          'language' => language
        }

        request(:get, '/fba/outbound/2020-07-01/returnReasonCodes', query: query, rdt: rdt)
      end

      # Requests that Amazon update the status of an order in the sandbox testing environment. This is a sandbox-only operation and must be directed to a sandbox endpoint. Refer to [Fulfillment Outbound Dynamic Sandbox Guide](https://developer-docs.amazon.com/sp-api/docs/fulfillment-outbound-dynamic-sandbox-guide) and [Selling Partner API sandbox](https://developer-docs.amazon.com/sp-api/docs/the-selling-partner-api-sandbox) for more information.
      #
      # @param body [Hash] The identifier assigned to the item by the seller when the fulfillment order was created. (SubmitFulfillmentOrderStatusUpdateRequest)
      # @param seller_fulfillment_order_id [String] The identifier assigned to the item by the seller when the fulfillment order was created.
      # @param rdt [Array<RDT::Resource>, nil] send a restricted data token for these resources
      # @return [AmazonSpClients::ApiResponse]
      def submit_fulfillment_order_status_update(body, seller_fulfillment_order_id, rdt: nil)
        request(:put, "/fba/outbound/2020-07-01/fulfillmentOrders/#{encode(seller_fulfillment_order_id)}/status", body: body, rdt: rdt)
      end

      # Updates and/or requests shipment for a fulfillment order with an order hold on it. **Usage Plan:** | Rate (requests per second) | Burst | | ---- | ---- | | 2 | 30 | The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
      #
      # @param body [Hash] UpdateFulfillmentOrderRequest parameter (UpdateFulfillmentOrderRequest)
      # @param seller_fulfillment_order_id [String] The identifier assigned to the item by the seller when the fulfillment order was created.
      # @param rdt [Array<RDT::Resource>, nil] send a restricted data token for these resources
      # @return [AmazonSpClients::ApiResponse]
      def update_fulfillment_order(body, seller_fulfillment_order_id, rdt: nil)
        request(:put, "/fba/outbound/2020-07-01/fulfillmentOrders/#{encode(seller_fulfillment_order_id)}", body: body, rdt: rdt)
      end
    end
  end
end
