# frozen_string_literal: true

# Generated by lib/generator (bundle exec rake generate). Do not edit.

require 'amazon_sp_clients/v2/api'

module AmazonSpClients
  module V2
    # The Selling Partner API for Orders
    #
    # The Selling Partner API for Orders returns orders information. This API supports the following types of orders: - FBM (Fulfilled by Merchant) - FBA (Fulfilled by Amazon) - read only - Amazon Fresh This API does not display order data that is more than two years old, except in the JP, AU, and SG marketplaces, for which data from 2016 and after is available.
    #
    # OpenAPI spec version: 2026-01-01
    class Orders2026 < Api
      # Returns the order that you specify. **Usage Plan:** | Rate (requests per second) | Burst | | ---- | ---- | | 0.5 | 30 | The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that are applied to the requested operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may receive higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api) in the Selling Partner API documentation.
      #
      # @param order_id [String] An Amazon-defined order identifier.
      # @param included_data [Array<String>, nil] A list of datasets to include in the response.
      # @return [AmazonSpClients::ApiResponse]
      def get_order(order_id, included_data: nil)
        query = {
          'includedData' => csv(included_data)
        }

        request(:get, "/orders/2026-01-01/orders/#{encode(order_id)}", query: query)
      end

      # Returns orders created or updated during the time period that you specify. You can filter the response for specific types of orders. **Usage Plan:** | Rate (requests per second) | Burst | | ---- | ---- | | 0.0056 | 20 | The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that are applied to the requested operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may receive higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api) in the Selling Partner API documentation.
      #
      # @param created_after [String, nil] The response includes orders created at or after this time. The date must be in [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) format. **Note**: You must provide exactly one of `createdAfter` and `lastUpdatedAfter` in your request. If `createdAfter` is provided, neither `lastUpdatedAfter` nor `lastUpdatedBefore` may be provided.
      # @param created_before [String, nil] The response includes orders created at or before this time. The date must be in [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) format. **Note**: If you include `createdAfter` in the request, `createdBefore` is optional, and if provided must be equal to or after the `createdAfter` date and at least two minutes before the time of the request. If `createdBefore` is provided, neither `lastUpdatedAfter` nor `lastUpdatedBefore` may be provided.
      # @param last_updated_after [String, nil] The response includes orders updated at or after this time. An update is any change made by Amazon or the seller, including changes to order status. The date must be in [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) format. **Note**: You must provide exactly one of `createdAfter` and `lastUpdatedAfter`. If `lastUpdatedAfter` is provided, neither `createdAfter` nor `createdBefore` may be provided.
      # @param last_updated_before [String, nil] The response includes orders updated at or before this time. An update is any change made by Amazon or the seller, including changes to order status. The date must be in [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) format. **Note**: If you include `lastUpdatedAfter` in the request, `lastUpdatedBefore` is optional, and if provided must be equal to or after the `lastUpdatedAfter` date and at least two minutes before the time of the request. If `lastUpdatedBefore` is provided, neither `createdAfter` nor `createdBefore` may be provided.
      # @param fulfillment_statuses [Array<String>, nil] A list of `FulfillmentStatus` values you can use to filter the results.
      # @param marketplace_ids [Array<String>, nil] The response includes orders that were placed in marketplaces you include in this list. Refer to [Marketplace IDs](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids) for a complete list of `marketplaceId` values.
      # @param fulfilled_by [Array<String>, nil] The response includes orders that are fulfilled by the parties that you include in this list.
      # @param max_results_per_page [Integer, nil] The maximum number of orders that can be returned per page. The value must be between 1 and 100. **Default:** 100.
      # @param pagination_token [String, nil] Pagination occurs when a request produces a response that exceeds the `maxResultsPerPage`. This means that the response is divided into individual pages. To retrieve the next page, you must pass the `nextToken` value as the `paginationToken` query parameter in the next request. You will not receive a `nextToken` value on the last page.
      # @param included_data [Array<String>, nil] A list of datasets to include in the response.
      # @return [AmazonSpClients::ApiResponse]
      def search_orders(created_after: nil, created_before: nil, last_updated_after: nil, last_updated_before: nil, fulfillment_statuses: nil, marketplace_ids: nil, fulfilled_by: nil, max_results_per_page: nil, pagination_token: nil, included_data: nil)
        query = {
          'createdAfter' => created_after,
          'createdBefore' => created_before,
          'lastUpdatedAfter' => last_updated_after,
          'lastUpdatedBefore' => last_updated_before,
          'fulfillmentStatuses' => csv(fulfillment_statuses),
          'marketplaceIds' => csv(marketplace_ids),
          'fulfilledBy' => csv(fulfilled_by),
          'maxResultsPerPage' => max_results_per_page,
          'paginationToken' => pagination_token,
          'includedData' => csv(included_data)
        }

        request(:get, '/orders/2026-01-01/orders', query: query)
      end
    end
  end
end
