# frozen_string_literal: true

# Generated by lib/generator (bundle exec rake generate). Do not edit.

require 'amazon_sp_clients/v2/api'

module AmazonSpClients
  module V2
    # Selling Partner API for Reports
    #
    # The Selling Partner API for Reports lets you retrieve and manage a variety of reports that can help selling partners manage their businesses.
    #
    # OpenAPI spec version: 2021-06-30
    class Reports2021 < Api
      # Cancels the report that you specify. Only reports with `processingStatus=IN_QUEUE` can be cancelled. Cancelled reports are returned in subsequent calls to the `getReport` and `getReports` operations. **Usage Plan:** | Rate (requests per second) | Burst | | ---- | ---- | | 0.0222 | 10 | The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
      #
      # @param report_id [String] The identifier for the report. This identifier is unique only in combination with a seller ID.
      # @param rdt [Array<RDT::Resource>, nil] send a restricted data token for these resources
      # @return [AmazonSpClients::ApiResponse]
      def cancel_report(report_id, rdt: nil)
        request(:delete, "/reports/2021-06-30/reports/#{encode(report_id)}", rdt: rdt)
      end

      # Cancels the report schedule that you specify. **Usage Plan:** | Rate (requests per second) | Burst | | ---- | ---- | | 0.0222 | 10 | The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
      #
      # @param report_schedule_id [String] The identifier for the report schedule. This identifier is unique only in combination with a seller ID.
      # @param rdt [Array<RDT::Resource>, nil] send a restricted data token for these resources
      # @return [AmazonSpClients::ApiResponse]
      def cancel_report_schedule(report_schedule_id, rdt: nil)
        request(:delete, "/reports/2021-06-30/schedules/#{encode(report_schedule_id)}", rdt: rdt)
      end

      # Creates a report. **Usage Plan:** | Rate (requests per second) | Burst | | ---- | ---- | | 0.0167 | 15 | The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
      #
      # @param body [Hash] Information required to create the report. (CreateReportSpecification)
      # @param rdt [Array<RDT::Resource>, nil] send a restricted data token for these resources
      # @return [AmazonSpClients::ApiResponse]
      def create_report(body, rdt: nil)
        request(:post, '/reports/2021-06-30/reports', body: body, rdt: rdt)
      end

      # Creates a report schedule. If a report schedule with the same report type and marketplace IDs already exists, it will be cancelled and replaced with this one. **Usage Plan:** | Rate (requests per second) | Burst | | ---- | ---- | | 0.0222 | 10 | The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
      #
      # @param body [Hash] Information required to create the report schedule. (CreateReportScheduleSpecification)
      # @param rdt [Array<RDT::Resource>, nil] send a restricted data token for these resources
      # @return [AmazonSpClients::ApiResponse]
      def create_report_schedule(body, rdt: nil)
        request(:post, '/reports/2021-06-30/schedules', body: body, rdt: rdt)
      end

      # Returns report details (including the `reportDocumentId`, if available) for the report that you specify. **Usage Plan:** | Rate (requests per second) | Burst | | ---- | ---- | | 2 | 15 | The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
      #
      # @param report_id [String] The identifier for the report. This identifier is unique only in combination with a seller ID.
      # @param rdt [Array<RDT::Resource>, nil] send a restricted data token for these resources
      # @return [AmazonSpClients::ApiResponse]
      def get_report(report_id, rdt: nil)
        request(:get, "/reports/2021-06-30/reports/#{encode(report_id)}", rdt: rdt)
      end

      # Returns the information required for retrieving a report document's contents. **Usage Plan:** | Rate (requests per second) | Burst | | ---- | ---- | | 0.0167 | 15 | The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
      #
      # @param report_document_id [String] The identifier for the report document.
      # @param rdt [Array<RDT::Resource>, nil] send a restricted data token for these resources
      # @return [AmazonSpClients::ApiResponse]
      def get_report_document(report_document_id, rdt: nil)
        request(:get, "/reports/2021-06-30/documents/#{encode(report_document_id)}", rdt: rdt)
      end

      # Returns report schedule details for the report schedule that you specify. **Usage Plan:** | Rate (requests per second) | Burst | | ---- | ---- | | 0.0222 | 10 | The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
      #
      # @param report_schedule_id [String] The identifier for the report schedule. This identifier is unique only in combination with a seller ID.
      # @param rdt [Array<RDT::Resource>, nil] send a restricted data token for these resources
      # @return [AmazonSpClients::ApiResponse]
      def get_report_schedule(report_schedule_id, rdt: nil)
        request(:get, "/reports/2021-06-30/schedules/#{encode(report_schedule_id)}", rdt: rdt)
      end

      # Returns report schedule details that match the filters that you specify. **Usage Plan:** | Rate (requests per second) | Burst | | ---- | ---- | | 0.0222 | 10 | The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
      #
      # @param report_types [Array<String>] A list of report types used to filter report schedules. Refer to [Report Type Values](https://developer-docs.amazon.com/sp-api/docs/report-type-values) for more information.
      # @param rdt [Array<RDT::Resource>, nil] send a restricted data token for these resources
      # @return [AmazonSpClients::ApiResponse]
      def get_report_schedules(report_types, rdt: nil)
        query = {
          'reportTypes' => csv(report_types)
        }

        request(:get, '/reports/2021-06-30/schedules', query: query, rdt: rdt)
      end

      # Returns report details for the reports that match the filters that you specify. **Usage Plan:** | Rate (requests per second) | Burst | | ---- | ---- | | 0.0222 | 10 | The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
      #
      # @param report_types [Array<String>, nil] A list of report types used to filter reports. Refer to [Report Type Values](https://developer-docs.amazon.com/sp-api/docs/report-type-values) for more information. When reportTypes is provided, the other filter parameters (processingStatuses, marketplaceIds, createdSince, createdUntil) and pageSize may also be provided. Either reportTypes or nextToken is required.
      # @param processing_statuses [Array<String>, nil] A list of processing statuses used to filter reports.
      # @param marketplace_ids [Array<String>, nil] A list of marketplace identifiers used to filter reports. The reports returned will match at least one of the marketplaces that you specify.
      # @param page_size [Integer, nil] The maximum number of reports to return in a single call.
      # @param created_since [String, nil] The earliest report creation date and time for reports to include in the response, in <a href='https://developer-docs.amazon.com/sp-api/docs/iso-8601'>ISO 8601</a> date time format. The default is 90 days ago. Reports are retained for a maximum of 90 days.
      # @param created_until [String, nil] The latest report creation date and time for reports to include in the response, in <a href='https://developer-docs.amazon.com/sp-api/docs/iso-8601'>ISO 8601</a> date time format. The default is now.
      # @param next_token [String, nil] A string token returned in the response to your previous request. `nextToken` is returned when the number of results exceeds the specified `pageSize` value. To get the next page of results, call the `getReports` operation and include this token as the only parameter. Specifying `nextToken` with any other parameters will cause the request to fail.
      # @param rdt [Array<RDT::Resource>, nil] send a restricted data token for these resources
      # @return [AmazonSpClients::ApiResponse]
      def get_reports(report_types: nil, processing_statuses: nil, marketplace_ids: nil, page_size: nil, created_since: nil, created_until: nil, next_token: nil, rdt: nil)
        query = {
          'reportTypes' => csv(report_types),
          'processingStatuses' => csv(processing_statuses),
          'marketplaceIds' => csv(marketplace_ids),
          'pageSize' => page_size,
          'createdSince' => created_since,
          'createdUntil' => created_until,
          'nextToken' => next_token
        }

        request(:get, '/reports/2021-06-30/reports', query: query, rdt: rdt)
      end
    end
  end
end
