# frozen_string_literal: true

# Generated by lib/generator (bundle exec rake generate). Do not edit.

require 'amazon_sp_clients/v2/api'

module AmazonSpClients
  module V2
    # Selling Partner API for Direct Fulfillment Inventory Updates
    #
    # The Selling Partner API for Direct Fulfillment Inventory Updates provides programmatic access to a direct fulfillment vendor's inventory updates.
    #
    # OpenAPI spec version: v1
    class VdfInventoryV1 < Api
      # Submits inventory updates for the specified warehouse for either a partial or full feed of inventory items. **Usage Plan:** | Rate (requests per second) | Burst | | ---- | ---- | | 10 | 10 | The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
      #
      # @param body [Hash] The request body containing the inventory update data to submit. (SubmitInventoryUpdateRequest)
      # @param warehouse_id [String] Identifier for the warehouse for which to update inventory.
      # @param rdt [Array<RDT::Resource>, nil] send a restricted data token for these resources
      # @return [AmazonSpClients::ApiResponse]
      def submit_inventory_update(body, warehouse_id, rdt: nil)
        request(:post, "/vendor/directFulfillment/inventory/v1/warehouses/#{encode(warehouse_id)}/items", body: body, rdt: rdt)
      end
    end
  end
end
