# frozen_string_literal: true

# Generated by lib/generator (bundle exec rake generate). Do not edit.

require 'amazon_sp_clients/v2/api'

module AmazonSpClients
  module V2
    # Selling Partner API for Direct Fulfillment Shipping
    #
    # The Selling Partner API for Direct Fulfillment Shipping provides programmatic access to a direct fulfillment vendor's shipping data.
    #
    # OpenAPI spec version: v1
    class VdfShippingV1 < Api
      # Returns a customer invoice based on the purchaseOrderNumber that you specify. **Usage Plan:** | Rate (requests per second) | Burst | | ---- | ---- | | 10 | 10 | The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
      #
      # @param purchase_order_number [String] Purchase order number of the shipment for which to return the invoice.
      # @param rdt [Array<RDT::Resource>, nil] send a restricted data token for these resources
      # @return [AmazonSpClients::ApiResponse]
      def get_customer_invoice(purchase_order_number, rdt: nil)
        request(:get, "/vendor/directFulfillment/shipping/v1/customerInvoices/#{encode(purchase_order_number)}", rdt: rdt)
      end

      # Returns a list of customer invoices created during a time frame that you specify. You define the  time frame using the createdAfter and createdBefore parameters. You must use both of these parameters. The date range to search must be no more than 7 days. **Usage Plan:** | Rate (requests per second) | Burst | | ---- | ---- | | 10 | 10 | The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
      #
      # @param created_after [String] Orders that became available after this date and time will be included in the result. Must be in ISO-8601 date/time format.
      # @param created_before [String] Orders that became available before this date and time will be included in the result. Must be in ISO-8601 date/time format.
      # @param ship_from_party_id [String, nil] The vendor warehouseId for order fulfillment. If not specified, the result will contain orders for all warehouses.
      # @param limit [Integer, nil] The limit to the number of records returned
      # @param sort_order [String, nil] Sort ASC or DESC by order creation date.
      # @param next_token [String, nil] Used for pagination when there are more orders than the specified result size limit. The token value is returned in the previous API call.
      # @param rdt [Array<RDT::Resource>, nil] send a restricted data token for these resources
      # @return [AmazonSpClients::ApiResponse]
      def get_customer_invoices(created_after, created_before, ship_from_party_id: nil, limit: nil, sort_order: nil, next_token: nil, rdt: nil)
        query = {
          'shipFromPartyId' => ship_from_party_id,
          'limit' => limit,
          'createdAfter' => created_after,
          'createdBefore' => created_before,
          'sortOrder' => sort_order,
          'nextToken' => next_token
        }

        request(:get, '/vendor/directFulfillment/shipping/v1/customerInvoices', query: query, rdt: rdt)
      end

      # Returns a packing slip based on the purchaseOrderNumber that you specify. **Usage Plan:** | Rate (requests per second) | Burst | | ---- | ---- | | 10 | 10 | The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
      #
      # @param purchase_order_number [String] The purchaseOrderNumber for the packing slip you want.
      # @param rdt [Array<RDT::Resource>, nil] send a restricted data token for these resources
      # @return [AmazonSpClients::ApiResponse]
      def get_packing_slip(purchase_order_number, rdt: nil)
        request(:get, "/vendor/directFulfillment/shipping/v1/packingSlips/#{encode(purchase_order_number)}", rdt: rdt)
      end

      # Returns a list of packing slips for the purchase orders that match the criteria specified. Date range to search must not be more than 7 days. **Usage Plan:** | Rate (requests per second) | Burst | | ---- | ---- | | 10 | 10 | The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
      #
      # @param created_after [String] Packing slips that became available after this date and time will be included in the result. Must be in ISO-8601 date/time format.
      # @param created_before [String] Packing slips that became available before this date and time will be included in the result. Must be in ISO-8601 date/time format.
      # @param ship_from_party_id [String, nil] The vendor warehouseId for order fulfillment. If not specified the result will contain orders for all warehouses.
      # @param limit [Integer, nil] The limit to the number of records returned
      # @param sort_order [String, nil] Sort ASC or DESC by packing slip creation date.
      # @param next_token [String, nil] Used for pagination when there are more packing slips than the specified result size limit. The token value is returned in the previous API call.
      # @param rdt [Array<RDT::Resource>, nil] send a restricted data token for these resources
      # @return [AmazonSpClients::ApiResponse]
      def get_packing_slips(created_after, created_before, ship_from_party_id: nil, limit: nil, sort_order: nil, next_token: nil, rdt: nil)
        query = {
          'shipFromPartyId' => ship_from_party_id,
          'limit' => limit,
          'createdAfter' => created_after,
          'createdBefore' => created_before,
          'sortOrder' => sort_order,
          'nextToken' => next_token
        }

        request(:get, '/vendor/directFulfillment/shipping/v1/packingSlips', query: query, rdt: rdt)
      end

      # Returns a shipping label for the purchaseOrderNumber that you specify. **Usage Plan:** | Rate (requests per second) | Burst | | ---- | ---- | | 10 | 10 | The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
      #
      # @param purchase_order_number [String] The purchase order number for which you want to return the shipping label. It should be the same purchaseOrderNumber as received in the order.
      # @param rdt [Array<RDT::Resource>, nil] send a restricted data token for these resources
      # @return [AmazonSpClients::ApiResponse]
      def get_shipping_label(purchase_order_number, rdt: nil)
        request(:get, "/vendor/directFulfillment/shipping/v1/shippingLabels/#{encode(purchase_order_number)}", rdt: rdt)
      end

      # Returns a list of shipping labels created during the time frame that you specify. You define that time frame using the createdAfter and createdBefore parameters. You must use both of these parameters. The date range to search must not be more than 7 days. **Usage Plan:** | Rate (requests per second) | Burst | | ---- | ---- | | 10 | 10 | The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
      #
      # @param created_after [String] Shipping labels that became available after this date and time will be included in the result. Must be in ISO-8601 date/time format.
      # @param created_before [String] Shipping labels that became available before this date and time will be included in the result. Must be in ISO-8601 date/time format.
      # @param ship_from_party_id [String, nil] The vendor warehouseId for order fulfillment. If not specified, the result will contain orders for all warehouses.
      # @param limit [Integer, nil] The limit to the number of records returned.
      # @param sort_order [String, nil] Sort ASC or DESC by order creation date.
      # @param next_token [String, nil] Used for pagination when there are more ship labels than the specified result size limit. The token value is returned in the previous API call.
      # @param rdt [Array<RDT::Resource>, nil] send a restricted data token for these resources
      # @return [AmazonSpClients::ApiResponse]
      def get_shipping_labels(created_after, created_before, ship_from_party_id: nil, limit: nil, sort_order: nil, next_token: nil, rdt: nil)
        query = {
          'shipFromPartyId' => ship_from_party_id,
          'limit' => limit,
          'createdAfter' => created_after,
          'createdBefore' => created_before,
          'sortOrder' => sort_order,
          'nextToken' => next_token
        }

        request(:get, '/vendor/directFulfillment/shipping/v1/shippingLabels', query: query, rdt: rdt)
      end

      # Submits one or more shipment confirmations for vendor orders. **Usage Plan:** | Rate (requests per second) | Burst | | ---- | ---- | | 10 | 10 | The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
      #
      # @param body [Hash] Request body containing the shipment confirmations data. (SubmitShipmentConfirmationsRequest)
      # @param rdt [Array<RDT::Resource>, nil] send a restricted data token for these resources
      # @return [AmazonSpClients::ApiResponse]
      def submit_shipment_confirmations(body, rdt: nil)
        request(:post, '/vendor/directFulfillment/shipping/v1/shipmentConfirmations', body: body, rdt: rdt)
      end

      # This API call is only to be used by Vendor-Own-Carrier (VOC) vendors. Calling this API will submit a shipment status update for the package that a vendor has shipped. It will provide the Amazon customer visibility on their order, when the package is outside of Amazon Network visibility. **Usage Plan:** | Rate (requests per second) | Burst | | ---- | ---- | | 10 | 10 | The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
      #
      # @param body [Hash] Request body containing the shipment status update data. (SubmitShipmentStatusUpdatesRequest)
      # @param rdt [Array<RDT::Resource>, nil] send a restricted data token for these resources
      # @return [AmazonSpClients::ApiResponse]
      def submit_shipment_status_updates(body, rdt: nil)
        request(:post, '/vendor/directFulfillment/shipping/v1/shipmentStatusUpdates', body: body, rdt: rdt)
      end

      # Creates a shipping label for a purchase order and returns a transactionId for reference. **Usage Plan:** | Rate (requests per second) | Burst | | ---- | ---- | | 10 | 10 | The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
      #
      # @param body [Hash] Request body containing one or more shipping labels data. (SubmitShippingLabelsRequest)
      # @param rdt [Array<RDT::Resource>, nil] send a restricted data token for these resources
      # @return [AmazonSpClients::ApiResponse]
      def submit_shipping_label_request(body, rdt: nil)
        request(:post, '/vendor/directFulfillment/shipping/v1/shippingLabels', body: body, rdt: rdt)
      end
    end
  end
end
