# frozen_string_literal: true

# Generated by lib/generator (bundle exec rake generate). Do not edit.

require 'amazon_sp_clients/v2/api'

module AmazonSpClients
  module V2
    # Selling Partner API for Direct Fulfillment Orders
    #
    # The Selling Partner API for Direct Fulfillment Orders provides programmatic access to a direct fulfillment vendor's order data.
    #
    # OpenAPI spec version: v1
    class VdfOrdersV1 < Api
      # Returns purchase order information for the purchaseOrderNumber that you specify. **Usage Plan:** | Rate (requests per second) | Burst | | ---- | ---- | | 10 | 10 | The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
      #
      # @param purchase_order_number [String] The order identifier for the purchase order that you want. Formatting Notes: alpha-numeric code.
      # @param rdt [Array<RDT::Resource>, nil] send a restricted data token for these resources
      # @return [AmazonSpClients::ApiResponse]
      def get_order(purchase_order_number, rdt: nil)
        request(:get, "/vendor/directFulfillment/orders/v1/purchaseOrders/#{encode(purchase_order_number)}", rdt: rdt)
      end

      # Returns a list of purchase orders created during the time frame that you specify. You define the time frame using the createdAfter and createdBefore parameters. You must use both parameters. You can choose to get only the purchase order numbers by setting the includeDetails parameter to false. In that case, the operation returns a list of purchase order numbers. You can then call the getOrder operation to return the details of a specific order. **Usage Plan:** | Rate (requests per second) | Burst | | ---- | ---- | | 10 | 10 | The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
      #
      # @param created_after [String] Purchase orders that became available after this date and time will be included in the result. Must be in ISO-8601 date/time format.
      # @param created_before [String] Purchase orders that became available before this date and time will be included in the result. Must be in ISO-8601 date/time format.
      # @param ship_from_party_id [String, nil] The vendor warehouse identifier for the fulfillment warehouse. If not specified, the result will contain orders for all warehouses.
      # @param status [String, nil] Returns only the purchase orders that match the specified status. If not specified, the result will contain orders that match any status.
      # @param limit [Integer, nil] The limit to the number of purchase orders returned.
      # @param sort_order [String, nil] Sort the list in ascending or descending order by order creation date.
      # @param next_token [String, nil] Used for pagination when there are more orders than the specified result size limit. The token value is returned in the previous API call.
      # @param include_details [String, nil] When true, returns the complete purchase order details. Otherwise, only purchase order numbers are returned.
      # @param rdt [Array<RDT::Resource>, nil] send a restricted data token for these resources
      # @return [AmazonSpClients::ApiResponse]
      def get_orders(created_after, created_before, ship_from_party_id: nil, status: nil, limit: nil, sort_order: nil, next_token: nil, include_details: nil, rdt: nil)
        query = {
          'shipFromPartyId' => ship_from_party_id,
          'status' => status,
          'limit' => limit,
          'createdAfter' => created_after,
          'createdBefore' => created_before,
          'sortOrder' => sort_order,
          'nextToken' => next_token,
          'includeDetails' => include_details
        }

        request(:get, '/vendor/directFulfillment/orders/v1/purchaseOrders', query: query, rdt: rdt)
      end

      # Submits acknowledgements for one or more purchase orders. **Usage Plan:** | Rate (requests per second) | Burst | | ---- | ---- | | 10 | 10 | The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
      #
      # @param body [Hash] The request body containing the acknowledgement to an order. (SubmitAcknowledgementRequest)
      # @param rdt [Array<RDT::Resource>, nil] send a restricted data token for these resources
      # @return [AmazonSpClients::ApiResponse]
      def submit_acknowledgement(body, rdt: nil)
        request(:post, '/vendor/directFulfillment/orders/v1/acknowledgements', body: body, rdt: rdt)
      end
    end
  end
end
