# frozen_string_literal: true

# This file was autogenerated, do not edit it 

require_relative "../../vendor/catalog_items_v0/lib/sp_catalog_items_v0.rb"

module AmazonSpClients
  CatalogItemsV0Api = AmazonSpClients::SpCatalogItemsV0::CatalogItemsV0Api
end