# frozen_string_literal: true

# This file was autogenerated, do not edit it 

require_relative "../../vendor/fba_small_and_light/lib/sp_fba_small_and_light.rb"

module AmazonSpClients
  FbaSmallAndLightApi = AmazonSpClients::SpFbaSmallAndLight::FbaSmallAndLightApi
end