# frozen_string_literal: true

# This file was autogenerated, do not edit it 

require_relative "../../vendor/feeds_2020/lib/sp_feeds_2020.rb"

module AmazonSpClients
  # Feeds2020Api = AmazonSpClients::SpFeeds2020::Feeds2020Api
end
