# frozen_string_literal: true

# This file was autogenerated, do not edit it 

require_relative "../../vendor/finances_v0/lib/sp_finances_v0.rb"

module AmazonSpClients
  FinancesV0Api = AmazonSpClients::SpFinancesV0::FinancesV0Api
end