# frozen_string_literal: true

# This file was autogenerated, do not edit it 

require_relative "../../vendor/fulfillment_outbound_2020/lib/sp_fulfillment_outbound_2020.rb"

module AmazonSpClients
  FulfillmentOutbound2020Api = AmazonSpClients::SpFulfillmentOutbound2020::FulfillmentOutbound2020Api
end