# frozen_string_literal: true

# This file was autogenerated, do not edit it 

require_relative "../../vendor/fulfillment_inbound_v0/lib/sp_fulfillment_inbound_v0.rb"

module AmazonSpClients
  FulfillmentInboundV0Api = AmazonSpClients::SpFulfillmentInboundV0::FulfillmentInboundV0Api
end