# frozen_string_literal: true

# This file was autogenerated, do not edit it 

require_relative "../../vendor/notifications/lib/sp_notifications.rb"

module AmazonSpClients
  NotificationsApi = AmazonSpClients::SpNotifications::NotificationsApi
end