# frozen_string_literal: true

# This file was autogenerated, do not edit it 

require_relative "../../vendor/orders_v0/lib/sp_orders_v0.rb"

module AmazonSpClients
  OrdersV0Api = AmazonSpClients::SpOrdersV0::OrdersV0Api
end
