# frozen_string_literal: true

# This file was autogenerated, do not edit it 

require_relative "../../vendor/services/lib/sp_services.rb"

module AmazonSpClients
  ServicesApi = AmazonSpClients::SpServices::ServicesApi
end