# frozen_string_literal: true

# This file was autogenerated, do not edit it 

require_relative "../../vendor/sales/lib/sp_sales.rb"

module AmazonSpClients
  SalesApi = AmazonSpClients::SpSales::SalesApi
end