# frozen_string_literal: true

# This file was autogenerated, do not edit it 

require_relative "../../vendor/shipping/lib/sp_shipping.rb"

module AmazonSpClients
# TODO: initialize or pass HTTP client...
end