# frozen_string_literal: true

# This file was autogenerated, do not edit it 

require_relative "../../vendor/sellers/lib/sp_sellers.rb"

module AmazonSpClients
  SellersApi = AmazonSpClients::SpSellers::SellersApi
end