# frozen_string_literal: true

# This file was autogenerated, do not edit it 

require_relative "../../vendor/tokens_2021/lib/sp_tokens_2021.rb"

module AmazonSpClients
# TODO: initialize or pass HTTP client...
end