# frozen_string_literal: true

# This file was autogenerated, do not edit it 

require_relative "../../vendor/vendor_orders/lib/sp_vendor_orders.rb"

module AmazonSpClients
  VendorOrdersApi = AmazonSpClients::SpVendorOrders::VendorOrdersApi
end