# frozen_string_literal: true

# This file was autogenerated, do not edit it 

require_relative "../../vendor/vendor_transaction_status/lib/sp_vendor_transaction_status.rb"

module AmazonSpClients
end