# frozen_string_literal: true

# This file was autogenerated, do not edit it 

require_relative "../../vendor/vendors_shipments/lib/sp_vendors_shipments.rb"

module AmazonSpClients
  VendorsShipmentsApi = AmazonSpClients::SpVendorsShipments::VendorsShipmentsApi
end