# frozen_string_literal: true

# This file was autogenerated, do not edit it 

require_relative "../../vendor/vdf_shipping_v1/lib/sp_vdf_shipping_v1.rb"

module AmazonSpClients
  VdfShippingV1Api = AmazonSpClients::SpVdfShippingV1::VdfShippingV1Api
end