# frozen_string_literal: true

# Generated by lib/generator (bundle exec rake generate). Do not edit.

require 'amazon_sp_clients/v2/client'

module AmazonSpClients
  module V2
    autoload :FbaInventory, 'amazon_sp_clients/v2/apis/fba_inventory'
    autoload :Feeds2021, 'amazon_sp_clients/v2/apis/feeds_2021'
    autoload :FulfillmentOutbound2020, 'amazon_sp_clients/v2/apis/fulfillment_outbound_2020'
    autoload :ListingsItems2021, 'amazon_sp_clients/v2/apis/listings_items_2021'
    autoload :OrdersV0, 'amazon_sp_clients/v2/apis/orders_v0'
    autoload :Reports2021, 'amazon_sp_clients/v2/apis/reports_2021'
    autoload :Tokens2021, 'amazon_sp_clients/v2/apis/tokens_2021'
    autoload :VdfInventoryV1, 'amazon_sp_clients/v2/apis/vdf_inventory_v1'
    autoload :VdfOrdersV1, 'amazon_sp_clients/v2/apis/vdf_orders_v1'
    autoload :VdfShippingV1, 'amazon_sp_clients/v2/apis/vdf_shipping_v1'
    autoload :VendorInvoices, 'amazon_sp_clients/v2/apis/vendor_invoices'
    autoload :VendorOrders, 'amazon_sp_clients/v2/apis/vendor_orders'
    autoload :VendorTransactionStatus, 'amazon_sp_clients/v2/apis/vendor_transaction_status'
    autoload :VendorsShipments, 'amazon_sp_clients/v2/apis/vendors_shipments'

    class Client
      # Selling Partner API for FBA Inventory
      # @return [FbaInventory]
      def fba_inventory = api(FbaInventory)

      # Selling Partner API for Feeds
      # @return [Feeds2021]
      def feeds_2021 = api(Feeds2021)

      # Selling Partner APIs for Fulfillment Outbound
      # @return [FulfillmentOutbound2020]
      def fulfillment_outbound_2020 = api(FulfillmentOutbound2020)

      # Selling Partner API for Listings Items
      # @return [ListingsItems2021]
      def listings_items_2021 = api(ListingsItems2021)

      # Selling Partner API for Orders
      # @return [OrdersV0]
      def orders_v0 = api(OrdersV0)

      # Selling Partner API for Reports
      # @return [Reports2021]
      def reports_2021 = api(Reports2021)

      # Selling Partner API for Tokens
      # @return [Tokens2021]
      def tokens_2021 = api(Tokens2021)

      # Selling Partner API for Direct Fulfillment Inventory Updates
      # @return [VdfInventoryV1]
      def vdf_inventory_v1 = api(VdfInventoryV1)

      # Selling Partner API for Direct Fulfillment Orders
      # @return [VdfOrdersV1]
      def vdf_orders_v1 = api(VdfOrdersV1)

      # Selling Partner API for Direct Fulfillment Shipping
      # @return [VdfShippingV1]
      def vdf_shipping_v1 = api(VdfShippingV1)

      # Selling Partner API for Retail Procurement Payments
      # @return [VendorInvoices]
      def vendor_invoices = api(VendorInvoices)

      # Selling Partner API for Retail Procurement Orders
      # @return [VendorOrders]
      def vendor_orders = api(VendorOrders)

      # Selling Partner API for Retail Procurement Transaction Status
      # @return [VendorTransactionStatus]
      def vendor_transaction_status = api(VendorTransactionStatus)

      # Selling Partner API for Retail Procurement Shipments
      # @return [VendorsShipments]
      def vendors_shipments = api(VendorsShipments)
    end
  end
end
